---
title: 'Step-by-step Assignment setup instructions RStudio Cloud and GitHub'
author: "Claire Duquennois"
date: "11/1/2022-Revised"
output:
  pdf_document:
    number_sections: yes
    toc: yes
  html_document:
    df_print: paged
    toc: yes
---

Setting up your workflow in RStudio Cloud and Github you will need to:

- Clone the project assignment in RStudio Cloud

- Create an empty GitHub Repo

- Push your project assignment to the new GitHub repo


To do this follow the steps below: 

# Clone the project assignment in RStudio Cloud

- Follow the link posted in the Canvas announcement to access the course's RStudio Cloud workspace

- Clone the homework assignment project to generate your own project space within the course workspace

# Create an empty GitHub Repo

- Generate an empty private GitHub repository: do not include any files when you create this repository (no README or .gitignore files)

- copy the url that is generated for this new repository and save it for the next step (it will look something like: https://github.com/my_username/my_new_repo_name.git )

# Push your project assignment to the new GitHub repo

In your project assignment space in RStudio Cloud type the following commands followed by enter into the terminal tab of the SW area of your project space. When prompted input your username and security token (this could be requested several times).


## Clear and previous GitHub configuration:

In cloning the project on RStudio cloud you may have also cloned existing git configurations. Let's check:  

`/cloud/project$ git remote -v`

If a set of url's are returned that look something like:

`origin  https://github.com/claireduq/MQE_Causal_PS2.git (fetch)`

`origin  https://github.com/claireduq/MQE_Causal_PS2.git (push)`


you will want to remove these to set them to your own repo. Let's remove them. Type:

`/cloud/project$ git remove origin`


## Set up your own GitHub configuration:


`/cloud/project$ git init`

`/cloud/project$ git add .`

`/cloud/project$ git config --global user.email "my_email@pitt.edu"`

`/cloud/project$ git config --global user.name "my_username"`

`/cloud/project$ git commit -m "first"`

`/cloud/project$ git remote add origin https://github.com/my_username/my_new_repo_name.git`

`/cloud/project$ git remote -v`

you should see your repo info appear now

`/cloud/project$ git push --set-upstream origin main`

(if for some reason this does not work try replacing main with master)

`/cloud/project$ git push`


You should now see your project files on GitHub. You can now push and pull changes to GitHub for version control and collaborative purposes. 


# For individual assignments:

- Add the TA and I as collaborators to your Github Repo. By the assignment due date, make sure you push a final version of your assignment's .Rmd file and the knit pdf or html file to your GitHub repo as that is where it will be graded. 


# For Group assignments:

Select a group leader. The group leader should:

- create a private repo named PSXX_name1_name2_name3. Initialize this repo with a README file.

- delete the README file so that the repo is empty but has a commit history. 

- Invite the other group members, the TA and I as collaborators. 

All group members: 

- Follow the link posted in the Canvas announcement to access the course's RStudio Cloud workspace

- Clone the homework assignment project to generate your own project space within the course workspace


- Fork the group repo and name it PSXX_my_name to your github account so that you now have an empty repo on github to "fill" with your RStudio cloud project

- copy the url that is generated for this repository and save it for the next step (it will look something like: https://github.com/my_username/PSXX_my_name.git )

- follow the same steps as detailed above to push your project assignment to this GitHub repo

- You will then proceed by generating pull requests and updates to the main group repo PSXX_name1_name2_name3 as you work. Remember to pull updates down to your folders and push your updates up to the group project frequently as you work to stay up to date on group progrss. 



